// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consumer.proto

package consumer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumerRequest struct {
	Id                   int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*ConsumerRequest_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ConsumerRequest) Reset()         { *m = ConsumerRequest{} }
func (m *ConsumerRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumerRequest) ProtoMessage()    {}
func (*ConsumerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{0}
}

func (m *ConsumerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerRequest.Unmarshal(m, b)
}
func (m *ConsumerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerRequest.Marshal(b, m, deterministic)
}
func (m *ConsumerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerRequest.Merge(m, src)
}
func (m *ConsumerRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumerRequest.Size(m)
}
func (m *ConsumerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerRequest proto.InternalMessageInfo

func (m *ConsumerRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConsumerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConsumerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConsumerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ConsumerRequest) GetAddresses() []*ConsumerRequest_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type ConsumerRequest_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerRequest_Address) Reset()         { *m = ConsumerRequest_Address{} }
func (m *ConsumerRequest_Address) String() string { return proto.CompactTextString(m) }
func (*ConsumerRequest_Address) ProtoMessage()    {}
func (*ConsumerRequest_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{0, 0}
}

func (m *ConsumerRequest_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerRequest_Address.Unmarshal(m, b)
}
func (m *ConsumerRequest_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerRequest_Address.Marshal(b, m, deterministic)
}
func (m *ConsumerRequest_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerRequest_Address.Merge(m, src)
}
func (m *ConsumerRequest_Address) XXX_Size() int {
	return xxx_messageInfo_ConsumerRequest_Address.Size(m)
}
func (m *ConsumerRequest_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerRequest_Address.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerRequest_Address proto.InternalMessageInfo

func (m *ConsumerRequest_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *ConsumerRequest_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ConsumerRequest_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ConsumerRequest_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ConsumerRequest_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type ConsumerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerResponse) Reset()         { *m = ConsumerResponse{} }
func (m *ConsumerResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumerResponse) ProtoMessage()    {}
func (*ConsumerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{1}
}

func (m *ConsumerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerResponse.Unmarshal(m, b)
}
func (m *ConsumerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerResponse.Marshal(b, m, deterministic)
}
func (m *ConsumerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerResponse.Merge(m, src)
}
func (m *ConsumerResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumerResponse.Size(m)
}
func (m *ConsumerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerResponse proto.InternalMessageInfo

func (m *ConsumerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConsumerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ConsumerFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumerFilter) Reset()         { *m = ConsumerFilter{} }
func (m *ConsumerFilter) String() string { return proto.CompactTextString(m) }
func (*ConsumerFilter) ProtoMessage()    {}
func (*ConsumerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_376dcb7dada8cc1b, []int{2}
}

func (m *ConsumerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerFilter.Unmarshal(m, b)
}
func (m *ConsumerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerFilter.Marshal(b, m, deterministic)
}
func (m *ConsumerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerFilter.Merge(m, src)
}
func (m *ConsumerFilter) XXX_Size() int {
	return xxx_messageInfo_ConsumerFilter.Size(m)
}
func (m *ConsumerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerFilter proto.InternalMessageInfo

func (m *ConsumerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*ConsumerRequest)(nil), "consumer.ConsumerRequest")
	proto.RegisterType((*ConsumerRequest_Address)(nil), "consumer.ConsumerRequest.Address")
	proto.RegisterType((*ConsumerResponse)(nil), "consumer.ConsumerResponse")
	proto.RegisterType((*ConsumerFilter)(nil), "consumer.ConsumerFilter")
}

func init() { proto.RegisterFile("consumer.proto", fileDescriptor_376dcb7dada8cc1b) }

var fileDescriptor_376dcb7dada8cc1b = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xef, 0x4a, 0xc3, 0x30,
	0x10, 0xc0, 0x97, 0x6e, 0xdd, 0x9f, 0x53, 0xea, 0x0c, 0x22, 0xb1, 0x9f, 0x6a, 0x3f, 0x15, 0x91,
	0x21, 0xf3, 0xab, 0x20, 0x32, 0x70, 0xf8, 0xb5, 0x3e, 0x41, 0x6d, 0x0f, 0x17, 0xdc, 0xda, 0x9a,
	0xcb, 0x90, 0xf9, 0x0a, 0xbe, 0x83, 0xcf, 0xe0, 0x23, 0x4a, 0xd2, 0x66, 0x03, 0xe7, 0xbe, 0xdd,
	0xef, 0x72, 0x77, 0xf9, 0xe5, 0x08, 0x04, 0x79, 0x55, 0xd2, 0x7a, 0x85, 0x6a, 0x52, 0xab, 0x4a,
	0x57, 0x7c, 0xe8, 0x38, 0xfe, 0xf1, 0xe0, 0x64, 0xd6, 0x42, 0x8a, 0xef, 0x6b, 0x24, 0xcd, 0x03,
	0xf0, 0x64, 0x21, 0x58, 0xc4, 0x12, 0x3f, 0xf5, 0x64, 0xc1, 0x39, 0xf4, 0xca, 0x6c, 0x85, 0xc2,
	0x8b, 0x58, 0x32, 0x4a, 0x6d, 0xcc, 0xcf, 0xc0, 0xc7, 0x55, 0x26, 0x97, 0xa2, 0x6b, 0x93, 0x0d,
	0x98, 0x6c, 0xbd, 0xa8, 0x4a, 0x14, 0xbd, 0x26, 0x6b, 0x81, 0xdf, 0xc3, 0x28, 0x2b, 0x0a, 0x85,
	0x44, 0x48, 0xc2, 0x8f, 0xba, 0xc9, 0xd1, 0xf4, 0x72, 0xb2, 0x35, 0xfa, 0x73, 0xfb, 0xe4, 0xa1,
	0x29, 0x4d, 0x77, 0x3d, 0xe1, 0x17, 0x83, 0x41, 0x9b, 0xe6, 0xe7, 0xd0, 0x27, 0xad, 0x10, 0xb5,
	0x15, 0x1c, 0xa5, 0x2d, 0x19, 0xc9, 0x5c, 0xea, 0x8d, 0x93, 0x34, 0xb1, 0xd1, 0x21, 0x9d, 0x69,
	0x74, 0x92, 0x16, 0xf8, 0x18, 0xba, 0x9f, 0xb2, 0x6e, 0x15, 0x4d, 0xc8, 0xaf, 0xe1, 0x54, 0xd2,
	0xf3, 0x42, 0xd6, 0xb5, 0x2c, 0x5f, 0xdb, 0x8b, 0x84, 0x1f, 0xb1, 0x64, 0x98, 0xee, 0x1f, 0xc4,
	0x77, 0x30, 0xde, 0x39, 0x53, 0x5d, 0x95, 0x84, 0x7b, 0x2b, 0x13, 0x30, 0xa0, 0x75, 0x9e, 0x9b,
	0x39, 0x9e, 0x9d, 0xe3, 0x30, 0xbe, 0x82, 0xc0, 0x75, 0x3f, 0xca, 0xa5, 0x46, 0x65, 0x6a, 0xdf,
	0x70, 0xf3, 0x51, 0xa9, 0xa2, 0x7d, 0x92, 0xc3, 0xe9, 0x37, 0x83, 0xa1, 0x2b, 0xe6, 0x73, 0x38,
	0x9e, 0xa3, 0x76, 0x48, 0x5c, 0xec, 0xaf, 0xb0, 0x19, 0x18, 0x5e, 0x1c, 0x5c, 0x6e, 0xdc, 0xb9,
	0x61, 0xfc, 0x09, 0x82, 0x99, 0xc2, 0x4c, 0xe3, 0x76, 0xf4, 0xe1, 0x86, 0x30, 0xfc, 0xef, 0xa8,
	0x79, 0x74, 0xdc, 0x79, 0xe9, 0xdb, 0xef, 0x74, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x80, 0xc0,
	0xa7, 0xc2, 0x60, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumerClient interface {
	GetConsumers(ctx context.Context, in *ConsumerFilter, opts ...grpc.CallOption) (Consumer_GetConsumersClient, error)
	CreateConsumer(ctx context.Context, in *ConsumerRequest, opts ...grpc.CallOption) (*ConsumerResponse, error)
}

type consumerClient struct {
	cc *grpc.ClientConn
}

func NewConsumerClient(cc *grpc.ClientConn) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) GetConsumers(ctx context.Context, in *ConsumerFilter, opts ...grpc.CallOption) (Consumer_GetConsumersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Consumer_serviceDesc.Streams[0], "/consumer.Consumer/GetConsumers", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerGetConsumersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Consumer_GetConsumersClient interface {
	Recv() (*ConsumerRequest, error)
	grpc.ClientStream
}

type consumerGetConsumersClient struct {
	grpc.ClientStream
}

func (x *consumerGetConsumersClient) Recv() (*ConsumerRequest, error) {
	m := new(ConsumerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *consumerClient) CreateConsumer(ctx context.Context, in *ConsumerRequest, opts ...grpc.CallOption) (*ConsumerResponse, error) {
	out := new(ConsumerResponse)
	err := c.cc.Invoke(ctx, "/consumer.Consumer/CreateConsumer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
type ConsumerServer interface {
	GetConsumers(*ConsumerFilter, Consumer_GetConsumersServer) error
	CreateConsumer(context.Context, *ConsumerRequest) (*ConsumerResponse, error)
}

func RegisterConsumerServer(s *grpc.Server, srv ConsumerServer) {
	s.RegisterService(&_Consumer_serviceDesc, srv)
}

func _Consumer_GetConsumers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumerFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServer).GetConsumers(m, &consumerGetConsumersServer{stream})
}

type Consumer_GetConsumersServer interface {
	Send(*ConsumerRequest) error
	grpc.ServerStream
}

type consumerGetConsumersServer struct {
	grpc.ServerStream
}

func (x *consumerGetConsumersServer) Send(m *ConsumerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Consumer_CreateConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).CreateConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.Consumer/CreateConsumer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).CreateConsumer(ctx, req.(*ConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Consumer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consumer.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsumer",
			Handler:    _Consumer_CreateConsumer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetConsumers",
			Handler:       _Consumer_GetConsumers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "consumer.proto",
}
